import React from "react";
import Card2 from "./Card2";
import img1 from "../components/assets/4.jpg";
const Items2 = () => {
  return (
    <div className="flex flex-wrap justify-evenly">
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
       <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
      <Card2
        image={
          img1
        }
        name={"Sandal"}
      />
    </div>
  );
};

export default Items2;
